name: "Build"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build
    - uses: actions/upload-artifact@v3
      with:
        name: instructions-pdf
        path: result/practical-session/instructions.pdf
    # build slides manually
    - run: nix shell nixpkgs#yarn --command yarn install
      working-directory: presentation
    - run: nix shell nixpkgs#yarn nixpkgs#chromium --command yarn build
      working-directory: presentation
    - uses: actions/upload-artifact@v3
      with:
        name: slides-html
        path: presentation/dist/slides.html
    - uses: actions/upload-artifact@v3
      with:
        name: slides-pdf
        path: presentation/dist/slides.pdf

